### PR TITLE
Ingest bitbucketUsername and githubUsername custom properties from Okta

### PR DESCRIPTION
**Pull request by erkangz**

### CODE REVIEW

**Comment by erkangz** [comment]
@philidem @aiwilliams is there a better way to ingest custom profile properties without having to know the property names?

**Comment by aiwilliams** [comment]
> is there a better way to ingest custom profile properties without having to know the property names?

The incoming object properties can be iterated and transferred to the entity, perhaps going through a transformation function to give them consistency (something like, map `first_name`, `FirstName` to `firstName` by "camelizing", or specific renames like `surname` -> `lastName`). There would need to be a reasonable default auto flattening of properties which are objects.

Is that what you're talking about @erkangz?

**Comment by erkangz** [comment]
> > is there a better way to ingest custom profile properties without having to know the property names?
> 
> The incoming object properties can be iterated and transferred to the entity, perhaps going through a transformation function to give them consistency (something like, map `first_name`, `FirstName` to `firstName` by "camelizing", or specific renames like `surname` -> `lastName`). There would need to be a reasonable default auto flattening of properties which are objects.
> 
> Is that what you're talking about @erkangz?

Yeah, that's it.  We don't have this transformation function in the SDK yet, correct?  We can move towards that direction in future iterations.

**Comment by aiwilliams** [comment]
> > > is there a better way to ingest custom profile properties without having to know the property names?
> > 
> > 
> > The incoming object properties can be iterated and transferred to the entity, perhaps going through a transformation function to give them consistency (something like, map `first_name`, `FirstName` to `firstName` by "camelizing", or specific renames like `surname` -> `lastName`). There would need to be a reasonable default auto flattening of properties which are objects.
> > Is that what you're talking about @erkangz?
> 
> Yeah, that's it. We don't have this transformation function in the SDK yet, correct? We can move towards that direction in future iterations.

We do not. I believe the Dualboot folks are planning to work toward something like this as well, and I informed them that we'd love to see it and move it into the SDK. I think it would be good to have a few of the projects take a stab at it, and then we can generalize the solution once we see the patterns.

**Pull request merged**
